### ISSUE TITLE
docxtpl 1.7 demo is not working on python 2.7

### ISSUE THREAD

**Issue by Malcriado415** [elapouya/python-docx-template#5]
Hello.  I just downloaded this library (version 1.7), and the basic [demo (under Quickstart-usage)][1] doesn't appear to be working:

```python
from docxtpl import DocxTemplate
doc = DocxTemplate("template2.docx")
context = { 'Date':'September 20, 2015','AddresseeFirst':'John','AddresseeLast':'Doe'}
doc.render(context)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/. . ./venv/lib/python2.7/site-packages/docxtpl/__init__.py", line 79, in render
    xml = self.build_xml(context)
  File "/Users/ . . . /venv/lib/python2.7/site-packages/docxtpl/__init__.py", line 68, in build_xml
    xml = self.get_xml()
  File "/Users/ . . . /venv/lib/python2.7/site-packages/docxtpl/__init__.py", line 29, in get_xml
    return etree.tostring(self.docx._element.body, encoding='unicode', pretty_print=True)
AttributeError: 'Document' object has no attribute '_element'
```

I'm running this on a venv running python 2.7.5, python-docx version 7.4 and jinja2 version 2.7.3.

Any advice would be much appreciated.  This looks like just the project I've been hoping to find.  

[1]:  http://docxtpl.readthedocs.org/en/latest/

**Comment by elapouya** [comment]
Could you try doxtpl previous version (0.1.6) :  pip install docxtpl==0.1.6

**Comment by elapouya** [comment]
Hello,

Could you send me the template2.docx you are using ?

Regards,

Eric

2015-09-21 9:27 GMT+02:00 Malcriado415 <notifications@github.com>:

**Comment by Malcriado415** [comment]
Thanks for responding.  Changing to version 1.6 did not help.  Also, I'm unable to attach the template file because of its file type.  

![image](https://cloud.githubusercontent.com/assets/6943665/9996056/17cb3476-603a-11e5-8802-afca9d317f70.png)

Do you have an email address I can send it to?    The entire contents of the template file are printed below:

![image](https://cloud.githubusercontent.com/assets/6943665/9996136/88ae7b80-603a-11e5-8cbb-1066817a670c.png)

**Comment by elapouya** [comment]
please send the docx here : ericdupo@gmail.com

Do you have created the docx with official microsoft word or something else
like staroffice ?

2015-09-21 17:27 GMT+02:00 Malcriado415 <notifications@github.com>:

**Comment by Malcriado415** [comment]
No, I created it with MSOffice (Word for Mac 2011).  Will send it now.  Thank you so much!

**Comment by Malcriado415** [comment]
It looks like this was caused by a problem with my dependencies.   After trying to install version 1.6, I ran **pip install -U docxtpl** to get the latest version (1.7).  This also updated my dependencies by uninstalling and reinstalling docxtpl python-docx jinja2 and lxml.

It looks like I had been running python-docx==0.7.4, jinja2==2.7.3 and lxml==3.4.0.  Everything looks to be working fine now (python-docx==0.8.5, jinja2==2.8 and lxml==3.4.4)  Thanks to Eric for looking at my template offline.
