### ISSUE TITLE
DocumentPart object has no attribute '_rels'.

### ISSUE THREAD

**Issue by theodore86** [elapouya/python-docx-template#541]
## Describe the bug

It seems like [python-docx](https://github.com/python-openxml/python-docx/releases/tag/v1.1.1) has released an new version:

```console
python-docx==1.1.1
docxtpl==0.16.8
```

```python
uri = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/header'
    def get_headers_footers(self, uri):
>       for relKey, val in self.docx._part._rels.items():
E       AttributeError: 'DocumentPart' object has no attribute '_rels'. Did you mean: 'rels'?
```

**Comment by msp-corbett** [comment]
I've hit the same issue and rolled back to python-docx 1.1.0 as a fix.

**Comment by joao-gabrielC** [comment]
> I've hit the same issue and rolled back to python-docx 1.1.0 as a fix.

Rolling back also fixed the issue for me.

**Comment by elapouya** [comment]
I am going to investigate about what's new in that python-docx version...

**Comment by elapouya** [comment]
I created the new docxtpl 0.17.0 : it requires python-docx 1.1.1+

Please, could you test ?

**Comment by lcpprop** [comment]
Yes, everything works perfectly for me. Thank you so much! How about the others?

**Comment by msp-corbett** [comment]
Yes, working with docxtpl 0.17.0 and python-docx 1.1.2. Thanks!

**Comment by theodore86** [comment]
Thank, i have already locked the dependencies so it is not an major issue, it works.
